### ISSUE TITLE
SFM freezes and crashes after pressing "Save"

### ISSUE THREAD

**Issue by bomberooi** [sonich2401/SM64_Save_File_Converter#2]
Happens on Windows 11

**Comment by sonich2401** [comment]
Hello and thanks for using my tool. Sorry I didn't see your issue. I've been busy with college. Could you give me some more info on what you were doing at the time? I've done extensive testing on windows so the specific situation (and if possible the save file you were using) would help me a ton in solving the crash.

Thanks again for using my tool!

**Comment by nadia8666** [comment]
@sonich2401
yea they are correct
latest **windows 11** as of right now
blank save crashes (freezes)
[save.zip](https://github.com/sonich2401/SM64_Save_File_Converter/files/10449082/save.zip)

**Comment by sonich2401** [comment]
> @sonich2401
> 
> yea they are correct
> 
> latest **windows 11** as of right now
> 
> blank save crashes (freezes)
> 
> [save.zip](https://github.com/sonich2401/SM64_Save_File_Converter/files/10449082/save.zip)
> 
> 

What save dump tool was used to make this save? Is it emu, z64, or Vdoc64?

Edit: looks like it is a n64 type. Turns out the issue is that the image loader can't find a image that is used in the save screen. Looking into the issue now

**Comment by dariuskrs** [comment]
HI, same issue for me locally on 
[savedata.zip](https://github.com/sonich2401/SM64_Save_File_Converter/files/10831391/savedata.zip)

I'm not deep enough in C++ to debug it myself, hope you can have a look and add your fix.
BTW what would help me too is if you had in your readme a How-To section to run and debug with WSL + VSCode; I do not have Visual Studio standard/pro/license.

**Comment by sonich2401** [comment]
I believe I have found a way to delay the crash until you close out of the program. Hopefully I can make a release soon but I am busy with college right now so when midterms die down I will try to get a fix out.

**Comment by nadia8666** [comment]
sick 👍

**Comment by sonich2401** [comment]
Hey all! Thanks for the wait. I finally fixed this bug entirely. It was a pain to get rid of the bug. 

You can find the latest release at this link

https://github.com/sonich2401/SM64_Save_File_Converter/releases/tag/v1.1
